apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ort-server-tasks
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: ort-server-tasks-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: ort-server-tasks
  apiGroup: rbac.authorization.k8s.io
